### ISSUE TITLE
Pass new growth curves within the time step to

### ISSUE THREAD

**Issue by paulrougieux** [cat-cfs/libcbm_py#67]
We want to implement a change of growth multiplier during the simulation. Annual growth multiplier would reflect change related to climate change and simulations of NPP evolution in the future. 

# Current status

In LIbcbm 2 The Current object returned within the time step by `rule_based_proc.pre_dynamics_func` has the following structure: 

```
cbm_vars = self.rule_based_proc.pre_dynamics_func(timestep, cbm_vars)
dir(cbm_vars)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_classifiers', '_flux', '_inventory', '_parameters', '_pools', '_state', 'classifiers', 'flux', 'inventory', 'parameters', 'pools', 'state']

```
It doesn't contain the growth curves

# Proposal

Add a data frame containing the growth curves to the object rule_based_proc.pre_dynamics_func.

**Comment by smorken** [comment]
The only way you could do this currently would be to re-initialize the model for each timestep. The merch vols get converted to Carbon curves at init time.  

Going to close this one for now since I don't plan on change that in the strictly "CBM-CFS3-matching" part of the libcbm code, but feel free to continue the discussion if I am missing something here.
